# STAR Methods

## Resource Availability

### Lead contact

Further information about resources should be directed to Scott Claessens 
(scott.claessens@gmail.com).

### Materials availability

This study did not generate new unique materials.

### Data and code availability

All data have been deposited on GitHub and are publicly available as of the date
of publication. DOIs are listed in the key resources table.

All original code has been deposited on GitHub and is publicly available as of 
the date of publication. DOIs are listed in the key resources table.

## Method Details

### Video searches and coding

Our video search was conducted on YouTube in July 2020. Searches were conducted
manually by the first author over a month-long period, using the same IP address
and not logged in with a YouTube user account. Search terms included 
"parrot using tool" and variants (e.g., "macaw using tool", "lorikeet using 
tool", "parakeet using tool"), "tool use in parrot", "parrot tool use", "parrot 
scratching itself" (included after we found several videos demonstrating 
self-care tool use in previous searches) and equivalent terms (e.g., "parrot 
preening itself", "parrot grooming itself", "parrot scratching"). For all 
species that did not display results including object manipulation or scratching 
behaviours, we also searched the species’ common name(s) + "tool use", as well 
as the species’ common name(s) + "scratching". We also searched for translations 
of the terms "parrot tool use" and "parrot scratching" in languages for all 
countries where bird ownership was reported as >5% [@GlobalGfkSurvey], namely, 
Turkish, Czech, Polish, French, Italian, Dutch, German, Russian, Spanish, 
Portuguese, and Mandarin. Browser search histories were not cleared between
searches.

When we found a relevant video, we also searched for similar content uploaded by 
the same person/channel. For each YouTube search conducted, we watched all 
relevant videos until we reached five consecutive videos that did not feature 
any parrots. At this point, we ended that search and initiated the next search. 
In line with previous recommendations [@Nelson2013], we planned to exclude any 
videos that consisted of four or more shots edited together so as to ensure the 
behaviours being observed were not edited or manipulated, but none of the videos 
obtained qualified for exclusion.

All videos featuring parrots manipulating objects were investigated for 
potential tool use or borderline tool use. We defined tool use as the 
manipulation of an unattached object as an extension of the beak or foot to 
achieve a goal towards another object, individual, or oneself [@Shumaker2011]. 
Borderline tool use was similarly defined, except that it involved the use of an 
object that was still attached to a substrate [@Seed2010]. For example, if 
individuals used a fallen feather or stick for self-scratching this was defined 
as tool use, but using one’s currently attached tail feathers or cage 
furnishings for the same purpose was defined as borderline tool use. 
Self-scratching had to involve slow and repeated movements of touching an object 
to one’s body (or, in the case of borderline tool use, rubbing repetitively 
against an attached object [@Sandor2020]).

All relevant videos were coded for video length, species, tool use presence 
(yes/borderline), tool use type (e.g., scratching, feeding), the object being 
used (e.g., feather, stick), tool use target, human interaction 
(talking or handing object to parrot, holding parrot), and the number of shots 
within each video. Our complete dataset also includes the name for each video, 
link, subject name, sex (as declared by owner, as most parrot species are not 
sexually dimorphic), publishing date, and dates found and coded.

Since YouTube is constantly growing and evolving in both its uploaded content 
and its proprietary recommendation algorithms, the same search strategy today 
would not return exactly the same videos as our search in July 2020. It is 
possible that some videos have since been deleted or more videos of parrot tool
use have since been uploaded. However, this does not affect our conclusions
about the number of parrot species found to use tools in our initial search.

### Data for parrot species

We collected data for 194 parrot species (Figures
\@ref(fig:plotPhylo2) - \@ref(fig:plotPhylo4)). We gathered feeding strategy 
data as a dichotomous variable ("generalist" or "specialist") from the 
EltonTraits ecological database [@Wilman2016]. As per the database, specialists 
were defined as species whose diet comprised at least 70% of a single food 
source. To calculate relative brain size, we collated data from the literature 
for all known body mass (g) and brain mass (g) values across 
parrots [@Flammer2001;@Iwaniuk2005;@Mazengenya2018;@Olkowicz2016;@Schuck2008;
@Silva2017]. For all species for which we obtained body and brain mass data, we 
calculated the encephalisation quotient (EQ) using the following 
formula [@Jerison1973]: $BrainWeight / (0.12 * BodyWeight(\frac{2}{3}))$. We 
found body mass and brain mass data for a total of 194 parrot species. This 
included all tool-using species in our video dataset, with the exception of 
three species: _Diopsittaca nobilis_, _Psittacara erythrogenys_, and _Coracopsis 
vasa_. For the latter, we used values for the closely related _Coracopsis 
nigra_. The other two species were excluded from the final dataset.

For modelling purposes, we coded research effort in both the scientific 
literature and the YouTube videos. For the scientific literature, we 
operationalised research effort as the number of papers published for each 
species' Latin name up to and including the first paper containing tool use for 
that species. If no tool use had been identified in the scientific literature 
for a species, then we coded the total number of papers published to date. We 
used the scientific database Scopus for coding the number of published papers. 
For the videos, we coded research effort as the number of search hits for each
species on YouTube. If tool use had been identified on YouTube, we estimated the
number of search hits when the first video of tool use was published on YouTube,
assuming linear growth of search hits since the inception of YouTube. If tool
use had not been identified, we used the current number of search hits.

For phylogenetic data, we used the phylogenetic tool at www.birdtree.org
[@Jetz2012] to compile 1000 posterior draws of phylogenetic trees for 174 of the 
194 parrot species for which both EQ and genomic data exist. A single maximum 
clade credibility tree was generated from these posterior draws for 
visualisation purposes. In our analyses, we iterated over posterior draws of the 
phylogeny to account for phylogenetic uncertainty.

## Quantification and Statistical Analysis

### Phylogenetic signal

We used the _fitDiscrete_ function in the _ape_ R package [@Paradis2019] to 
calculate phylogenetic signal, for both the pre-survey and post-survey tool use 
data. We iterated the model over 100 posterior parrot phylogenies to incorporate 
phylogenetic uncertainty.

### Causal model of tool use

To infer unobserved probabilities of tool use across parrots, we proposed a 
causal model of observed tool use (Figure \@ref(fig:plotDAG)). We assumed that 
observed tool use in the scientific literature and in the videos is caused by 
both the unobserved presence or absence of tool use and research effort, proxied
by the number of papers published on a species and the number of videos
published on a species. Tool users are more likely to be observed if they are
well studied, but understudied tool users may go undetected. In addition, based
on theory, we also assumed that unobserved tool use is caused by feeding 
strategy and relative brain size [@Lefebvre2004;@Lefebvre1997;@Lefebvre2002;
@Ducatez2015;@Sol2005;@Overington2011;@HenkeVonDerMalsburg2020]. Finally, we 
assumed that shared phylogenetic history causes unobserved confounding and 
non-independence in unobserved tool use, feeding strategy, and relative brain 
size across the parrot phylogeny.

### Bayesian phylogenetic survival cure model

Given our proposed causal model, we constructed a statistical model to impute 
unobserved probabilities of tool use and test existing theories of the evolution 
of tool use in parrots. To understand the model, suppose that we have the 
following observed variables for parrot species $i$. For the scientific 
literature, we declare $\text{N}_{\text{Lit},i}$ as the number of papers 
published before and up to tool use identification for species $i$ (or, if tool 
use has not been identified, the total number of papers published for species 
$i$) and $\text{T}_{\text{Lit},i}$ as a binary variable stating whether (1) or 
not (0) tool use has yet been observed in the scientific literature for species 
$i$. For the videos, we declare $\text{N}_{\text{Vid},i}$ as the 
number of videos published before and up to tool use identification for species 
$i$ (or, if tool use has not been identified, the total number of videos 
published for species $i$) and $\text{T}_{\text{Vid},i}$ as a binary variable 
stating whether (1) or not (0) tool use has yet been observed in the 
videos for species $i$. Additionally, $\text{F}_i$ and 
$\text{EQ}_i$ are feeding strategy and encephalisation quotient values for 
species $i$ and we have a phylogenetic distance matrix $D$ that describes the 
patristic distances between all parrot species.

We assume that species $i$ is a non-tool-user with some 
probability $p_i$. We also assume that tool use is identified in the scientific 
literature and the videos at constant rates $\lambda_{\text{Lit}}$ 
and $\lambda_{\text{Vid}}$ following exponential survival functions. Given these 
assumptions, we can then describe the different ways in which variables 
$\text{N}_\text{Lit}$ and $\text{N}_\text{Vid}$ can be distributed. Focusing on 
the scientific literature, if tool use has been observed 
($\text{T}_{\text{Lit},i} = 1$), then the likelihood for 
$\text{N}_{\text{Lit},i}$ is:

\begin{align}
\text{Pr}(\text{N}_{\text{Lit},i}|\text{T}_{\text{Lit},i} = 1,p_i,\lambda_\text{Lit}) = (1-p_i)\cdot\text{Exponential}(\text{N}_{\text{Lit},i}|\lambda_\text{Lit})
\end{align}

On the other hand, if tool use has not yet been observed 
($\text{T}_{\text{Lit},i} = 0$), there are two ways that the outcome variable 
could have been realised. First, the species could be a non-tool-user with 
probability $p_i$. Second, the species could be a tool-user with probability 
($1 - p_i$) that has been censored and has not had its tool use measured yet. 
Together, then, the likelihood for $\text{N}_{\text{Lit},i}$ is:

\begin{align}
\text{Pr}(\text{N}_{\text{Lit},i}|\text{T}_{\text{Lit},i} = 0,p_i,\lambda_\text{Lit}) = p_i + ((1-p_i)\cdot\text{Exponential-CCDF}(\text{N}_{\text{Lit},i}|\lambda_\text{Lit}))
\end{align}

The Exponential-CCDF function allows for the censored nature of the data. The 
same data generating process is assumed to underlie the videos.

We define the mixture likelihood $\text{SurvivalCure}$ as the distribution 
above, with parameters $p$ (the probability of being a non-tool-user) 
and $\lambda$ (the rate of the exponential distribution). We use an 
Ornstein-Uhlenbeck Gaussian process [@McElreath2020] to model phylogenetic 
covariance. Below, we specify the full model with priors:

\begin{align}
N_{\text{Lit},i} &\sim \text{SurvivalCure}(\lambda_{\text{Lit},i}, p_{i}) \\
N_{\text{Vid},i} &\sim \text{SurvivalCure}(\lambda_{\text{Vid},i}, p_{i}) \nonumber \\
\lambda_{\text{Lit},i} &= 1 / \text{exp}(\gamma_\text{Lit}) \nonumber \\
\lambda_{\text{Vid},i} &= 1 / \text{exp}(\gamma_\text{Vid}) \nonumber \\
\text{logit}(p_{i}) &= \alpha_{\text{FEEDING}[i]} + \beta\text{EQ}_{i} +  k_{\text{SPECIES}[i]} \nonumber \\
\begin{pmatrix}k_{1}\\k_{2}\\...\\k_{n}\\\end{pmatrix}
&\sim \text{MVNormal}
\begin{pmatrix}\begin{pmatrix}0\\0\\...\\0\\\end{pmatrix},\bf{K}\end{pmatrix} \nonumber \\
\bf{K}_{ij} &= \eta^2\text{exp}(-\rho^2D_{ij}) \nonumber \\
\gamma_\text{Lit}, \gamma_\text{Vid}, \alpha_{1,2}, \beta &\sim \text{Normal(0, 1)} \nonumber \\
\eta^2, \rho^2 &\sim \text{Exponential(0.5)} \nonumber
\end{align}

The priors for this model produce reasonable prior predictions of the 
probabilities of tool use for each parrot species (Figure
\@ref(fig:plotSurvCure7)), but a sensitivity analysis revealed that the ranking 
and posterior probabilities reported in the main text were robust to modifying 
these priors (Figure \@ref(fig:plotSurvCure8)). We estimated the 
posterior distribution of this model using Hamiltonian Monte Carlo as 
implemented in Stan version 2.26.1 [@Stan2020]. We ran the model for 4000 
samples, with 2000 warmup samples, and iterated the model over 100 posterior 
parrot phylogenies to incorporate phylogenetic uncertainty. R-hat values and 
effective sample sizes suggested that the model converged normally. Trace plots 
are reported in Figure \@ref(fig:plotTrace). We report 
equal-tailed credible intervals to describe the posterior distribution of this 
model in the main text.

To validate our method, we fitted the model to 100 simulated datasets with known 
parameters. The model was able to successfully recover those parameters 
(Figure \@ref(fig:plotSurvCureSim)). We also ran a 
leave-one-species-out exercise to ensure that we could accurately predict known 
tool users. We repeated this approach for each known tool user by setting 
observed tool use to zero. Cross-validation results are reported in the main 
text.

### Ancestral state reconstruction

To determine whether the identification of novel tool-using species has 
implications for our understanding of the evolutionary origins of tool use in 
parrots, we fitted three exploratory ancestral state reconstruction models. We 
used the _ancThresh_ function from the _phytools_ R package [@phytools], 
iterating the function over 100 posterior parrot phylogenies. This function 
estimates discrete ancestral states by assuming the evolution of a latent 
continuous variable following an Ornstein-Uhlenbeck process. We fitted this 
model to three different outcome variables: (_i_) presence vs. absence of tool 
use in scientific literature only, (_ii_) presence vs. absence of tool use in 
literature and/or videos, and (_iii_) the median predicted probabilities of tool 
use from the phylogenetic survival cure model.

### Reproducibility

All analyses were conducted in R v4.2.1. [@RCoreTeam]. Visualisations were 
produced using the _ggtree_[@ggtree], _ggplot2_ [@Wickham2016], and _cowplot_ 
[@Wilke2020] packages. The manuscript was reproducibly generated using the 
_targets_ [@Landau2021] and _papaja_ [@Aust2022] packages. Code to reproduce all 
analyses and figures can be found here: 
https://github.com/ScottClaessens/phyloParrot
